### PR TITLE
Initial work for health check

### PR DESCRIPTION
**Pull request by sperrys**
Add a health check for the relevant open Baltimore data endpoints. Script currently assumes python environment @ ../venv/bin/python.  This is likely subject to change. 

For each endpoint, 

1) Make sure the endpoint is alive by making a HEAD request to the url. In some cases, a HEAD request is not allowed, so we fallback to a GET request
2) Make sure the endpoint's last updated date is within 90 days

If an endpoint fails either check 1 or 2, alert open Baltimore. The alerting mechanism itself is still TODO. 

Multiprocessing is used to make the execution time more reasonable

### CODE REVIEW

**Comment by sperrys** [comment]
@JasonInBmore The current commits in the branch should get the script mostly functional. Definitely try it out when you can and lmk what you think.

The remaining work that I can see atm:
- Include a cached file of previous endpoints to handle the endpoint deletion case
- Wire up the alerting mechanism (do we have the form api available?) 
- Figure out how to package/deploy on Github Actions

Thoughts?

**Comment by jjhale** [comment]
Corresponding [ticket](https://github.com/city-of-baltimore/open_baltimore_baltimore-civic-project/issues/3) and [epic](https://github.com/city-of-baltimore/open_baltimore_baltimore-civic-project/issues/5)

**Comment by JasonInBmore** [comment]
This is fantastic! Thanks so much for your work on this. I had a meeting yesterday with the IT/GIS folks who manage the technical resources of open Baltimore, and to my surprise, they were really excited about this, too.

I'm wondering why there's a 405 error for this endpoint: https://egisdata.baltimorecity.gov/egis/rest/services/Housing/DHCD_Open_Baltimore_Datasets/FeatureServer/3/query?outFields=*&where=1%3D1&f=geojson which resolves a geoJSON in a browser. Let me know if you have any ideas. I'll look into it too.

**Comment by JasonInBmore** [comment]
@sperrys 

Include a cached file of previous endpoints to handle the endpoint deletion case
- I love it!
Wire up the alerting mechanism (do we have the form api available?)
- Working on api endpoint where this can be sent. There's some sensitivity about publicly sharing endpoints that can interact with our official systems. If we can't use the City's microsoft or Atlassian endpoints for notifications, do you have other ideas on this.
Figure out how to package/deploy on Github Actions
- this is a fantastic idea worth pursuing. I have _no_ idea about github actions but looking forward to learning more. 

If we can't do an alert to one of our systems, or at least yet, would it be possible to post a running output of the alerts somewhere in a human-readable format?

**Comment by JasonInBmore** [comment]
this is fantastic

**Comment by sperrys** [comment]
@JasonInBmore 

Cool that there's some buy-in from the IT folks. 

In response to some of your points, 

-  From what I was able to tell, a couple of the endpoints do not allow HEAD requests (this is how we are checking liveness without downloading the actual data itself). If the endpoint doesn't allow a head request, it will give back a [405 response](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405). If this happens, the script should fallback to making a typical GET request (like the browser geo-json example) for the check.  Pretty sure that's whats happening with that specific endpoint.

- As a stop gap measure while the form api is in progress, we could write the results to a local file in the repo? We would need to figure out a sane output format, but it should be relatively easy to script. My one concern is that this would still require someone remembering to visit this repo weekly to get the results?  Maybe getting an email from Github actions about the workflow running would be enough reminder to go check?

- If I find sometime in the next week, I'll work on the deleted endpoint case. 

- Hopefully we can follow up / brainstorm at the next civic tech meeting

**Pull request merged**
